# Generated by Django 6.0.4 on 2026-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='inquiry_type',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
